name: GitHub Action
run-name: ${{ github.actor }}
on: 
    push:
        branches:
            - master
jobs:
  Run-TruffleHog-OSS:
    runs-on: ubuntu-latest
    steps:
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.47.0